# Generated by Django 3.2.7 on 2022-02-15 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewiew',
            name='image',
            field=models.ImageField(default=1, upload_to='client_image'),
            preserve_default=False,
        ),
    ]
