# Generated by Django 3.2.7 on 2022-02-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='image',
            field=models.ImageField(default=1, upload_to='objects_image/'),
            preserve_default=False,
        ),
    ]
