# Generated by Django 3.2.7 on 2022-02-13 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0002_objects_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='objects',
            name='image',
        ),
        migrations.AddField(
            model_name='objects',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objects',
            name='over',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objects',
            name='price',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='objects',
            name='start',
            field=models.CharField(default=2022, max_length=250),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ObjectsImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='objects_image/')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='objects.objects')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
    ]
