# Generated by Django 3.2.7 on 2022-02-13 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0005_auto_20220213_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectsimages',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_image', to='objects.objects'),
        ),
    ]
